owner: FogSwim # GitHub username
repo: xfar-uptime # GitHub repository name
sites: # List of endpoints to track
  - name: FogSwim
    url: https://www.fogswim.com/
assignees: # Users to assign downtime issues (optional)
  - madhu-sachan
status-website: # Status website (optional)
  baseUrl: /xfar-uptime
  name: FogSwim Technologies # Status website title
